name: moltbot
region: tor  # Toronto (default)
# Available regions: nyc, ams, sfo, sgp, lon, fra, blr, syd, tor

# Note: This is a reference config. For Tailscale networking,
# use .do/deploy.template.yaml which deploys as a worker.

workers:
  - name: moltbot
    dockerfile_path: /Dockerfile
    instance_count: 1
    instance_size_slug: apps-s-2vcpu-4gb
    envs:
      # Required
      - key: TS_AUTHKEY
        scope: RUN_TIME
        type: SECRET
      - key: SETUP_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: MOLTBOT_STATE_DIR
        value: /data/.moltbot
      - key: MOLTBOT_WORKSPACE_DIR
        value: /data/workspace
      # Tailscale configuration
      - key: TS_HOSTNAME
        value: moltbot
      - key: TS_USERSPACE
        value: "true"
      - key: TS_SOCKET
        value: /tmp/tailscaled.sock
      # Recommended
      - key: MOLTBOT_GATEWAY_TOKEN
        scope: RUN_TIME
        type: SECRET
      # Optional: Litestream + Spaces persistence
      # Uncomment these to enable SQLite backup to DO Spaces
      # - key: LITESTREAM_ACCESS_KEY_ID
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: LITESTREAM_SECRET_ACCESS_KEY
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: SPACES_ENDPOINT
      #   value: tor1.digitaloceanspaces.com
      # - key: SPACES_BUCKET
      #   value: moltbot-backup
      # Optional: Gradient AI
      # - key: GRADIENT_API_KEY
      #   scope: RUN_TIME
      #   type: SECRET
