name: clawdbot
region: tor  # Toronto (default)
# Available regions: nyc, ams, sfo, sgp, lon, fra, blr, syd, tor

services:
  - name: clawdbot
    image:
      registry_type: GHCR
      registry: digitalocean-labs
      repository: clawdbot-appplatform
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb  # 1 shared vCPU, 2GB RAM, ~$25/mo
    http_port: 8080
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 10
    envs:
      # Required
      - key: PORT
        value: "8080"
      - key: SETUP_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: CLAWDBOT_STATE_DIR
        value: /data/.clawdbot
      - key: CLAWDBOT_WORKSPACE_DIR
        value: /data/workspace
      # Gateway mode: lan for public HTTP access
      - key: CLAWDBOT_GATEWAY_MODE
        value: lan
      # Recommended
      - key: CLAWDBOT_GATEWAY_TOKEN
        scope: RUN_TIME
        type: SECRET
      # Optional: Litestream + Spaces persistence
      # Uncomment these to enable SQLite backup to DO Spaces
      # - key: LITESTREAM_ACCESS_KEY_ID
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: LITESTREAM_SECRET_ACCESS_KEY
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: SPACES_ENDPOINT
      #   value: tor1.digitaloceanspaces.com
      # - key: SPACES_BUCKET
      #   value: clawdbot-backup
      # Optional: Gradient AI
      # - key: GRADIENT_API_KEY
      #   scope: RUN_TIME
      #   type: SECRET
