#!/command/with-contenv bash
# Fix permissions on /etc/cron.d directory and files

echo "[permissions] Fixing cron.d permissions"

# /etc/cron.d - directory should be 755, files should be 644
if [ -d /etc/cron.d ]; then
  chmod 755 /etc/cron.d
  chown root:root /etc/cron.d
  find /etc/cron.d -type f -exec chmod 644 {} \;
  find /etc/cron.d -type f -exec chown root:root {} \;
fi
